version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    depends_on:
      - redis
    command: >
      sh -c "npm install &&
             npx playwright install chromium --with-deps &&
             node index.js"
    volumes:
      - .:/app
    working_dir: /app

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
