version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    command: sh -c "npx playwright install chromium --with-deps && node index.js"
  redis:
    image: redis:latest
    ports:
      - "6379:6379" 