version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3001}:3001"
    env_file:
      - .env
    depends_on:
      - redis
    command: >
      sh -c "chmod +x wait-for-it.sh && \
             ./wait-for-it.sh redis:6379 -- \
             npm install && \
             npx playwright install chromium --with-deps && \
             node index.js"
    volumes:
      - .:/app
    working_dir: /app

  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
