services:
  - type: web
    name: my-node-app
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: my-redis
          property: connectionString
      - key: QUEUE_CONCURRENCY
        value: "1"

  - type: redis
    name: my-redis
    plan: free
    ipAllowList: [] # only allow internal connections
    maxmemoryPolicy: noeviction # recommended for queues 