services:
  - type: web
    name: my-node-app
    env: node
    plan: free
    buildCommand: |
      npm install
      npx playwright install chromium --with-deps
    startCommand: node index.js
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: my-redis
          property: connectionString

  - type: redis
    name: my-redis
    plan: free
    ipAllowList: [] # only allow internal connections
    maxmemoryPolicy: noeviction # recommended for queues 